config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :pins
  get 'inicio/contact'
  get 'inicio/index'
  root 'inicio#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def contact
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/inicio/contact.html.erb
<h1>Inicio#contact</h1>
<p>Find me in app/views/inicio/contact.html.erb</p>

app/views/inicio/index.html.erb
<div class="container">
    <h1 class="jumbotron"><a href="/inicio/contact">Pinterest</h1></a>
</div>

<div class="container__fluid">
    <div class="row">

        <div class="columna col-lg-4">
            <div class=" page-header">
                <h1>titulo</h1>
            </div>
            <p class="labes label-danger">Enim dolor duis amet irure voluptate exercitation do elit ipsum magna culpa
                nisi. Consectetur mollit sint anim Lorem. Dolor est et non dolore incididunt ad. Labore voluptate nisi
                elit cillum Lorem. Deserunt anim dolor excepteur tempor do voluptate sit sint et excepteur consequat
                officia. Consequat velit irure fugiat minim sunt amet nisi fugiat do nisi. Ipsum occaecat pariatur
                cillum commodo officia ea eiusmod laboris.</p>
        </div>
        <div class="columna col-lg-4">
            <div class=" page-header">
                <h1>titulo</h1>
            </div>
            <p class="labes label-danger">loremTempor adipisicing laborum consectetur in. Cupidatat aliquip sint culpa
                Lorem sunt ipsum do amet. Excepteur excepteur eiusmod quis consequat do. Ut esse labore labore eiusmod
                proident mollit. Anim velit ullamco aliqua cillum est esse. Non non ipsum tempor amet non duis sunt ea.
                Veniam velit proident consectetur magna ea nostrud cillum culpa ipsum excepteur deserunt.</p>
        </div>
        <div class="columna col-lg-4">
            <div class=" page-header">
                <h1>titulo</h1>
            </div>
            <p class="labes label-danger">Laboris dolore excepteur ex sunt cillum eiusmod. Proident reprehenderit magna
                tempor nisi voluptate adipisicing sit nisi ullamco non esse Lorem adipisicing. Mollit fugiat duis duis
                eiusmod. Officia consequat ex anim cillum aliquip qui duis voluptate tempor ad id consequat nisi
                ullamco. Lorem veniam velit sint adipisicing. Adipisicing qui anim culpa eiusmod anim do velit ex eu
                incididunt nostrud magna.</p>
        </div>


    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header"><a class="navbar-brand" href="<%=pins_path%>">
        <img alt="Brand" src="..."></a>
      </div>
    </div>
  </nav>
    
    <%= yield %>

<%# <div class="panel panel-danger">
  <div class="panel-footer">Panel footer</div>
</div> %>



  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container__fluid">
<h1>Pins</h1>

    <% @pins.each do |pin| %>
  <div class="col-lg-4">  
    <div class="thumbnail">
      <%= image_tag(pin.photo, :class => 'img-responsive') %>
      <%# la linea de arriba sirve para indicar que es una imagen y no un string cons sus clases de boostrap %>
      <%= pin.description%>
      <br>
      <%= link_to 'Mostrar', pin , :class =>'btn btn-danger' %>
      <%= link_to 'Edit', edit_pin_path(pin) , :class =>'btn btn-danger' %>
      <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } , :class =>'btn btn-danger' %>
    </div>
    </div>
    <% end %>


<br>
</div>
<%= link_to 'New Pin', new_pin_path, :class => 'btn btn-danger col-lg-12  mb-4' %>
<br>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style =>'width:500px')  %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>